version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: jobboard_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  
  django:
    build: ./jobboardsystem
    container_name: jobboard_webapi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./jobboardsystem:/app
    ports:
      - "8000:8000"
    env_file:
      - ./jobboardsystem/.env
    depends_on:
      - rabbitmq
      - redis 

  celery_worker:
    build: ./jobboardsystem
    container_name: jobboard_celery
    command: celery -A jobboardsystem worker --loglevel=info
    volumes:
      - ./jobboardsystem:/app
    env_file:
      - ./jobboardsystem/.env
    depends_on:
      - rabbitmq
      - redis 
      - django

  flower:
    build: ./jobboardsystem
    container_name: jobboard_flower
    command: celery -A jobboardsystem flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - ./jobboardsystem/.env
    depends_on:
      - rabbitmq
      - redis 
      - django
  
  redis:
    image: redis:7.2-alpine
    container_name: jobboard_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 
    command: redis-server --appendonly yes

      
volumes:
  rabbitmq_data:
  redis_data: 