version: '3.8'

services:
  # ─── SERVICE 1: BROKER RABBITMQ ───
  rabbitmq:
    image: rabbitmq:3-management
    container_name: jobboard_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  
  # ─── SERVICE 2: DJANGO WEB API ───
  web:
    build: ./jobboardsystem
    container_name: jobboard_webapi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./jobboardsystem:/app
    ports:
      - "8000:8000"
    env_file:
      - ./jobboardsystem/.env
    depends_on:
      - rabbitmq
      - redis 

  # ─── SERVICE 3: CELERY WORKER (Xử lý tác vụ ngầm) ───
  celery_worker:
    build: ./jobboardsystem
    container_name: jobboard_celery
    command: celery -A jobboardsystem worker --loglevel=info
    volumes:
      - ./jobboardsystem:/app
    env_file:
      - ./jobboardsystem/.env
    depends_on:
      - rabbitmq
      - redis 
      - web

  # ─── SERVICE 4: FLOWER (Giám sát Celery) ───
  flower:
    build: ./jobboardsystem
    container_name: jobboard_flower
    command: celery -A jobboardsystem flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - ./jobboardsystem/.env
    depends_on:
      - rabbitmq
      - redis 
      - web
  
  # ─── SERVICE 5: REDIS ───
  redis:
    image: redis:7.2-alpine
    container_name: jobboard_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 
    command: redis-server --appendonly yes # Bật chế độ lưu dữ liệu xuống ổ đĩa tránh bị mất khi sập nguồn

      
volumes:
  rabbitmq_data:
  redis_data: 