# Generated by Django 6.0.3 on 2026-04-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_company_owner_user_avatar_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
