# Generated by Django 6.0.3 on 2026-05-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0003_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
