# Generated by Django 6.0.3 on 2026-05-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0004_employerprofile_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
