# Generated by Django 6.0.3 on 2026-05-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0005_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('featured_job', 'Tin tuyển dụng nổi bật'), ('priority_application', 'Hồ sơ ứng viên ưu tiên')], default='featured_job', max_length=30),
        ),
    ]
