# Generated by Django 6.0.3 on 2026-05-02 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0006_application_is_priority_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='jobboard.application'),
        ),
    ]
