# Generated by Django 6.0.3 on 2026-05-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0006_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
