# Generated by Django 6.0.3 on 2026-05-02 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0007_payment_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('package_type', models.CharField(choices=[('featured_job', 'Tin tuyển dụng nổi bật'), ('priority_application', 'Hồ sơ ứng viên ưu tiên')], max_length=30)),
                ('level', models.IntegerField(choices=[(1, 'VIP1'), (2, 'VIP2'), (3, 'VIP3')])),
                ('duration_days', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['package_type', 'level'],
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-priority_level', '-created_at')},
        ),
        migrations.AddField(
            model_name='application',
            name='priority_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='priority_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='featured_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='featured_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='featured_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-featured_score'], name='jobboard_jo_feature_b09dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_featured'], name='jobboard_jo_is_feat_3fe538_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-featured_priority', '-created_at'], name='jobboard_jo_feature_666dda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('package_type', 'level')},
        ),
        migrations.AddField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='jobboard.package'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='jobboard_pa_status_4a84d9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='jobboard_pa_payment_5517d6_idx'),
        ),
    ]
