# Generated by Django 6.0.3 on 2026-05-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0008_package_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employer_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
