# Generated by Django 6.0.3 on 2026-05-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0009_application_employer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
