# Generated by Django 6.0.3 on 2026-05-11 04:45

import cloudinary.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0010_application_rating_job_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cv_file'),
        ),
        migrations.AlterField(
            model_name='application',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='cv_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cv_file'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate', 'job'], name='jobboard_ap_candida_d9e45d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='jobboard_ap_status_554873_idx'),
        ),
    ]
