import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const CONTAINER_PADDING = 20;

export const Colors = {
  bg:         '#F5F7FA',
  surface:    '#FFFFFF',
  border:     '#EAECF0',
  accent:     '#2563EB',
  accentLight:'#EFF6FF', 
  green:      '#16A34A',
  yellow:     '#D97706',
  red:        '#DC2626',
  purple:     '#7C3AED',
  text:       '#111827',
  textMuted:  '#9AA5B4',
  textSub:    '#6B7280',
  textPrimary:'#111827',
  textSec:    '#6B7280',
  pending:    '#D97706', 
  pendingBg:  '#FEF3C7',
  pendingBdr: '#FDE68A',
  approved:   '#16A34A',
  approvedBg: '#F0FDF4',
  rejected:   '#DC2626',
  rejectedBg: '#FEF2F2',
};

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: Colors.bg,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: CONTAINER_PADDING,
    paddingTop: Platform.OS === 'ios' ? 60 : 20,
    paddingBottom: 20,
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: Colors.text,
    letterSpacing: -0.5,
  },
  headerSub: {
    fontSize: 13,
    color: Colors.textMuted,
    marginTop: 2,
  },
  refreshIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  refreshIconText: {
    fontSize: 20,
    color: Colors.accent,
    fontWeight: '600',
  },
  scroll: {
    paddingHorizontal: CONTAINER_PADDING,
    paddingTop: 20,
    paddingBottom: 40,
  },
  overviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 20,
  },
  overviewCard: {
    width: (SCREEN_WIDTH - (CONTAINER_PADDING * 2) - 12) / 2,
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  overviewIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  overviewIcon: {
    fontSize: 18,
  },
  overviewValue: {
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  overviewLabel: {
    fontSize: 12,
    color: Colors.textMuted,
    fontWeight: '600',
    marginTop: 4,
  },
  section: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.text,
  },
  periodRow: {
    flexDirection: 'row',
    backgroundColor: Colors.bg,
    borderRadius: 10,
    padding: 4,
    marginBottom: 20,
    alignSelf: 'flex-start',
  },
  periodBtn: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 8,
  },
  periodBtnActive: {
    backgroundColor: Colors.surface,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  periodBtnText: {
    fontSize: 13,
    color: Colors.textMuted,
    fontWeight: '600',
  },
  periodBtnTextActive: {
    color: Colors.accent,
    fontWeight: '700',
  },
  barColumn: {
    alignItems: 'center',
    width: 55,
    marginRight: 8,
  },
  barValueLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: Colors.textSub,
    marginBottom: 4,
  },
  barTrack: {
    height: 100,
    width: 16,
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    justifyContent: 'flex-end',
  },
  barFill: {
    width: '100%',
    borderRadius: 8,
  },
  barXLabel: {
    fontSize: 10,
    color: Colors.textMuted,
    marginTop: 8,
    textAlign: 'center',
  },
  centered: {
    flex: 1,
    backgroundColor: Colors.bg,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  emptyText: {
    color: Colors.textMuted,
    fontSize: 14,
    textAlign: 'center',
    paddingVertical: 30,
  },
});
export const approvalStyles = StyleSheet.create({
    root:           { flex: 1, backgroundColor: Colors.bg },
    centered:       { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: Colors.bg },
 
    // Header
    header:         { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 14, backgroundColor: Colors.surface, borderBottomWidth: 1, borderBottomColor: Colors.border },
    headerTitle:    { fontSize: 20, fontWeight: '700', color: Colors.textPrimary, letterSpacing: -0.3 },
    headerSub:      { fontSize: 13, color: Colors.textSec, marginTop: 2 },
    refreshBtn:     { width: 38, height: 38, borderRadius: 19, backgroundColor: Colors.accentLight, justifyContent: 'center', alignItems: 'center' },
    refreshBtnText: { fontSize: 20, color: Colors.accent },
 
    // Tabs
    tabScroll:      { backgroundColor: Colors.surface, borderBottomWidth: 1, borderBottomColor: Colors.border, maxHeight: 48, flexGrow: 0 },
    tabContainer:   { paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center' },
    tab:            { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 14, marginRight: 4, borderBottomWidth: 2, borderBottomColor: 'transparent' },
    tabText:        { fontSize: 13, color: Colors.textSec },
    tabBadge:       { marginLeft: 6, minWidth: 20, height: 20, borderRadius: 10, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 5 },
    tabBadgeText:   { fontSize: 11, fontWeight: '700' },
 
    // List
    listContent:    { paddingHorizontal: 16, paddingTop: 12 },
 
    // Card
    card:               { backgroundColor: Colors.surface, borderRadius: 12, marginBottom: 12, padding: 14, borderWidth: 1, borderColor: Colors.border },
    cardTop:            { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
    companyLogoPlaceholder: { width: 44, height: 44, borderRadius: 10, backgroundColor: Colors.accentLight, justifyContent: 'center', alignItems: 'center' },
    companyLogoText:    { fontSize: 18, fontWeight: '700', color: Colors.accent },
    cardTitle:          { fontSize: 15, fontWeight: '600', color: Colors.textPrimary, flex: 1 },
    cardCompany:        { fontSize: 13, color: Colors.textSec, marginTop: 2 },
    statusBadge:        { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 20, borderWidth: 1, marginLeft: 8 },
    statusBadgeText:    { fontSize: 11, fontWeight: '600' },
    cardMeta:           { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 10 },
    metaTag:            { fontSize: 12, color: Colors.textSec, backgroundColor: Colors.bg, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
    cardFooter:         { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    cardTime:           { fontSize: 12, color: Colors.textMuted },
 
    // Quick actions
    quickActions:    { flexDirection: 'row', gap: 8 },
    quickReject:     { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 8, borderWidth: 1, borderColor: '#FECACA', backgroundColor: Colors.rejectedBg },
    quickRejectText: { fontSize: 13, fontWeight: '600', color: Colors.rejected },
    quickApprove:    { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 8, backgroundColor: Colors.approved },
    quickApproveText:{ fontSize: 13, fontWeight: '600', color: '#fff' },
 
    // Rejection note
    rejectionNote:      { marginTop: 10, padding: 10, backgroundColor: Colors.rejectedBg, borderRadius: 8, borderLeftWidth: 3, borderLeftColor: Colors.rejected },
    rejectionNoteLabel: { fontSize: 11, fontWeight: '700', color: Colors.rejected, marginBottom: 2 },
    rejectionNoteText:  { fontSize: 12, color: '#991B1B' },
 
    // Empty state
    empty:      { alignItems: 'center', paddingVertical: 60 },
    emptyIcon:  { fontSize: 48, marginBottom: 12 },
    emptyTitle: { fontSize: 16, fontWeight: '600', color: Colors.textPrimary, marginBottom: 6 },
    emptyDesc:  { fontSize: 14, color: Colors.textSec, textAlign: 'center' },
 
    // Reject Modal
    overlay:              { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center', padding: 20 },
    modalCard:            { backgroundColor: Colors.surface, borderRadius: 16, width: '100%', maxWidth: 400, padding: 24 },
    modalHeader:          { alignItems: 'center', marginBottom: 20 },
    modalIconWrap:        { width: 52, height: 52, borderRadius: 26, backgroundColor: Colors.rejectedBg, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
    modalIcon:            { fontSize: 22, color: Colors.rejected },
    modalTitle:           { fontSize: 18, fontWeight: '700', color: Colors.textPrimary, marginBottom: 4 },
    modalSub:             { fontSize: 13, color: Colors.textSec, textAlign: 'center' },
    modalLabel:           { fontSize: 13, fontWeight: '600', color: Colors.textPrimary, marginBottom: 8 },
    modalInput:           { borderWidth: 1, borderColor: Colors.border, borderRadius: 10, padding: 12, fontSize: 14, color: Colors.textPrimary, backgroundColor: Colors.bg, minHeight: 100 },
    modalActions:         { flexDirection: 'row', gap: 10, marginTop: 20 },
    cancelBtn:            { flex: 1, paddingVertical: 12, borderRadius: 10, borderWidth: 1, borderColor: Colors.border, alignItems: 'center' },
    cancelBtnText:        { fontSize: 14, fontWeight: '600', color: Colors.textSec },
    rejectConfirmBtn:     { flex: 1, paddingVertical: 12, borderRadius: 10, backgroundColor: Colors.rejected, alignItems: 'center', justifyContent: 'center' },
    rejectConfirmBtnText: { fontSize: 14, fontWeight: '600', color: '#fff' },
 
    // Detail Modal
    detailOverlay:       { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
    detailCard:          { backgroundColor: Colors.surface, borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '90%' },
    handleBar:           { width: 40, height: 4, backgroundColor: Colors.border, borderRadius: 2, alignSelf: 'center', marginTop: 10, marginBottom: 4 },
    detailHeader:        { flexDirection: 'row', alignItems: 'flex-start', padding: 20, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: Colors.border },
    detailTitle:         { fontSize: 18, fontWeight: '700', color: Colors.textPrimary, marginBottom: 4 },
    detailCompany:       { fontSize: 14, color: Colors.textSec },
    closeBtn:            { width: 32, height: 32, borderRadius: 16, backgroundColor: Colors.bg, justifyContent: 'center', alignItems: 'center', marginLeft: 10 },
    closeBtnText:        { fontSize: 14, color: Colors.textSec },
    detailScroll:        { paddingHorizontal: 20 },
    infoGrid:            { paddingVertical: 16, gap: 10 },
    infoRow:             { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
    infoLabel:           { fontSize: 13, color: Colors.textSec, flex: 1 },
    infoValue:           { fontSize: 13, color: Colors.textPrimary, fontWeight: '500', flex: 2, textAlign: 'right' },
    detailSection:       { paddingVertical: 14, borderTopWidth: 1, borderTopColor: Colors.border },
    detailSectionTitle:  { fontSize: 13, fontWeight: '700', color: Colors.textSec, marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.5 },
    detailBody:          { fontSize: 14, color: Colors.textPrimary, lineHeight: 22 },
    skillWrap:           { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    skillChip:           { paddingHorizontal: 12, paddingVertical: 5, backgroundColor: Colors.accentLight, borderRadius: 20 },
    skillChipText:       { fontSize: 12, fontWeight: '500', color: Colors.accent },
    detailActions:       { flexDirection: 'row', gap: 12, padding: 20, borderTopWidth: 1, borderTopColor: Colors.border },
    detailRejectBtn:     { flex: 1, paddingVertical: 14, borderRadius: 12, borderWidth: 1.5, borderColor: Colors.rejected, alignItems: 'center' },
    detailRejectBtnText: { fontSize: 15, fontWeight: '700', color: Colors.rejected },
    detailApproveBtn:    { flex: 2, paddingVertical: 14, borderRadius: 12, backgroundColor: Colors.approved, alignItems: 'center', justifyContent: 'center' },
    detailApproveBtnText:{ fontSize: 15, fontWeight: '700', color: '#fff' },
});