import { StyleSheet, Dimensions, Platform } from 'react-native';
import styles, { GlobalColors } from '../../styles/Styles';

const { width: SW, height: SH } = Dimensions.get('window');
const PAD = 20;

export const Colors = {
    bg:          GlobalColors.bg,
    surface:     GlobalColors.surface,
    border:      GlobalColors.border,
    accent:      GlobalColors.primary,
    accentLight: '#EFF6FF',
    accentBdr:   '#C5D0FF',
    green:       '#16A34A',
    yellow:      '#D97706',
    red:         '#DC2626',
    danger:      GlobalColors.danger,
    dangerBg:    GlobalColors.dangerBg,
    dangerBdr:   '#FECACA',
    purple:      '#7C3AED',
    text:        GlobalColors.text,
    textMuted:   GlobalColors.textMuted,
    textSub:     GlobalColors.textSec,
    textSec:     GlobalColors.textSec,
    pending:     '#D97706',
    pendingBg:   '#FEF3C7',
    pendingBdr:  '#FDE68A',
    approved:    '#16A34A',
    approvedBg:  '#F0FDF4',
    rejected:    '#DC2626',
    rejectedBg:  '#FEF2F2',
};

export default StyleSheet.create({
    ...styles,

    root:    { flex: 1, backgroundColor: Colors.bg },
    centered:{ flex: 1, backgroundColor: Colors.bg, justifyContent: 'center', alignItems: 'center', padding: 40 },

    interview: {
        header: {
            flexDirection: 'row', alignItems: 'center',
            backgroundColor: Colors.accent,
            paddingHorizontal: 16, paddingVertical: 14, gap: 12,
        },
        backBtn: { 
            width: 36, height: 36, borderRadius: 18, 
            backgroundColor: 'rgba(255,255,255,.2)', 
            justifyContent: 'center', alignItems: 'center' 
        },
        headerTitle: { color: '#fff', fontSize: 17, fontWeight: '700' },
        headerSub:   { color: '#BFDBFE', fontSize: 12, marginTop: 1 },
        countBubble: { backgroundColor: '#fff', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 3 },
        countText:   { color: Colors.accent, fontSize: 13, fontWeight: '700' },

        cardBadgeRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
        badge:        { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
        badgeIcon:    { marginRight: 4 },
        badgeScheduled: { backgroundColor: '#16A34A' },
        badgePending:   { backgroundColor: '#9CA3AF' },
        badgeText:      { color: '#fff', fontSize: 11, fontWeight: '700' },
        badgeNotified:  { flexDirection: 'row', alignItems: 'center', backgroundColor: '#DCFCE7', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4 },
        badgeNotifiedText: { color: '#16A34A', fontSize: 11, fontWeight: '600' },

        cardName:    { fontSize: 16, fontWeight: '700', color: Colors.text, marginBottom: 2 },
        cardJob:     { fontSize: 13, color: Colors.textSec, marginBottom: 1 },
        cardCompany: { fontSize: 13, color: Colors.textSec, marginBottom: 10 },

        scheduleBox: { backgroundColor: '#EFF6FF', borderRadius: 10, padding: 12, gap: 6 },
        scheduleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 6 },
        scheduleTime:{ fontSize: 14, fontWeight: '700', color: '#1D4ED8', flex: 1 },
        scheduleLoc: { fontSize: 13, color: Colors.text, flex: 1 },
        mapBtn:      { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4, alignSelf: 'flex-start' },
        mapBtnText:  { color: Colors.accent, fontSize: 12, fontWeight: '600' },

        noScheduleHint: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 4 },
        noScheduleText: { color: '#9CA3AF', fontSize: 13 },

        emptyWrap:  { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40, gap: 12, marginTop: 80 },
        emptyTitle: { fontSize: 17, fontWeight: '700', color: Colors.text, textAlign: 'center' },
        emptyDesc:  { fontSize: 14, color: Colors.textSec, textAlign: 'center', lineHeight: 20 },

        modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,.45)', justifyContent: 'flex-end' },
        modalSheet:   { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, maxHeight: '92%' },
        handleBar:    { width: 40, height: 4, backgroundColor: '#D1D5DB', borderRadius: 4, alignSelf: 'center', marginBottom: 16 },
        modalTitle:   { fontSize: 18, fontWeight: '800', color: Colors.text, marginBottom: 16, textAlign: 'center' },

        summaryBox:  { backgroundColor: '#EFF6FF', borderRadius: 12, padding: 14, marginBottom: 20 },
        summaryName: { fontSize: 15, fontWeight: '700', color: Colors.text },
        summaryJob:  { fontSize: 13, color: Colors.textSec, marginTop: 2 },

        fieldLabel: { fontSize: 13, fontWeight: '600', color: Colors.text, marginBottom: 6, marginTop: 14 },
        required:   { color: Colors.danger },
        fieldInput: { backgroundColor: Colors.bg, borderWidth: 1, borderColor: Colors.border, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10, fontSize: 14, color: Colors.text },
        fieldInputMulti: { height: 80, textAlignVertical: 'top', paddingTop: 10 },

        dtRow:      { flexDirection: 'row', gap: 10 },
        dtBtn:      { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: Colors.accentLight, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, borderWidth: 1, borderColor: Colors.accentBdr },
        dtBtnText: { color: Colors.accent, fontSize: 14, fontWeight: '600' },

        toggleRow:   { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.bg, borderRadius: 12, padding: 14, marginTop: 16, gap: 12 },
        toggleLabel: { fontSize: 14, fontWeight: '600', color: Colors.text },
        toggleSub:   { fontSize: 12, color: Colors.textMuted, marginTop: 2 },

        modalActions: { flexDirection: 'row', gap: 12, marginTop: 20 },
        cancelBtn:    { flex: 1, paddingVertical: 13, borderRadius: 12, borderWidth: 1, borderColor: Colors.border, alignItems: 'center' },
        cancelBtnText:{ fontSize: 15, color: Colors.textSec, fontWeight: '600' },
        saveBtn:      { flex: 2, paddingVertical: 13, borderRadius: 12, backgroundColor: Colors.accent, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 6 },
        saveBtnDisabled: { opacity: 0.7 },
        saveBtnText:  { fontSize: 15, color: '#fff', fontWeight: '700' },
        spacing:      { height: 20 }
    },

    header: {
        flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
        paddingHorizontal: PAD,
        paddingTop: Platform.OS === 'ios' ? 60 : 20,
        paddingBottom: 20,
        backgroundColor: Colors.surface,
        borderBottomWidth: 1, borderBottomColor: Colors.border, zIndex: 10,
    },
    headerTitle: { fontSize: 22, fontWeight: '800', color: Colors.text, letterSpacing: -0.5 },
    headerSub:   { fontSize: 13, color: Colors.textMuted, marginTop: 2 },

    pageHeader: {
        flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
        paddingHorizontal: PAD, paddingVertical: 16,
        backgroundColor: Colors.surface,
        borderBottomWidth: 1, borderBottomColor: Colors.border,
    },
    pageHeaderTitle: { fontSize: 20, fontWeight: '700', color: Colors.text },
    pageHeaderSub:   { fontSize: 13, color: Colors.textSec, marginTop: 2 },

    addBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: Colors.accent, justifyContent: 'center', alignItems: 'center' },

    card: {
        backgroundColor: Colors.surface, borderRadius: 16, padding: 16, marginBottom: 16,
        shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 3,
    },
    cardFeatured: { borderWidth: 2, shadowOpacity: 0.15, shadowRadius: 12, elevation: 6 },
    cardTop:      { flexDirection: 'row', alignItems: 'center' },
    cardLogo:     { width: 52, height: 52, borderRadius: 12, borderWidth: 1, borderColor: Colors.border },
    cardLogoPlaceholder: { width: 52, height: 52, borderRadius: 12, backgroundColor: Colors.accentLight, justifyContent: 'center', alignItems: 'center' },
    cardLogoText: { fontSize: 22, fontWeight: '700', color: Colors.accent },
    cardTitle:    { fontSize: 16, fontWeight: '700', color: Colors.text },
    cardSub:      { fontSize: 13, color: Colors.textSec, marginTop: 3 },
    cardActions:  { flexDirection: 'row', gap: 8 },

    editIconBtn:   { width: 36, height: 36, borderRadius: 10, backgroundColor: Colors.accentLight, justifyContent: 'center', alignItems: 'center' },
    deleteIconBtn: { width: 36, height: 36, borderRadius: 10, backgroundColor: Colors.dangerBg,   justifyContent: 'center', alignItems: 'center' },

    divider:      { height: 1, backgroundColor: Colors.border, marginVertical: 12 },
    infoGrid:     { gap: 10 },
    infoRow:      { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
    infoIconWrap: { width: 30, height: 30, borderRadius: 8, backgroundColor: Colors.accentLight, justifyContent: 'center', alignItems: 'center', marginTop: 2 },
    infoLabel:    { fontSize: 11, color: Colors.textMuted, fontWeight: '500', textTransform: 'uppercase', letterSpacing: 0.5 },
    infoValue:    { fontSize: 14, color: Colors.text, marginTop: 1 },
    descWrap:     { marginTop: 14, backgroundColor: Colors.bg, borderRadius: 10, padding: 12 },
    descLabel:    { fontSize: 11, color: Colors.textMuted, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 6 },

    emptyIconWrap:{ width: 96, height: 96, borderRadius: 48, backgroundColor: Colors.accentLight, justifyContent: 'center', alignItems: 'center', marginBottom: 20 },
    emptyTitle:   { fontSize: 18, fontWeight: '700', color: Colors.text, textAlign: 'center' },
    emptyDesc:    { fontSize: 14, color: Colors.textSec, textAlign: 'center', marginTop: 8, lineHeight: 21 },
    emptyBtn:     { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: Colors.accent, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 12, marginTop: 24 },
    emptyBtnText: { color: '#fff', fontWeight: '600', fontSize: 15 },

    listContent:   { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 40 },
    loadingFooter: { paddingVertical: 16 },

    filterContainer: { paddingHorizontal: 16, paddingVertical: 10, backgroundColor: Colors.surface, borderBottomWidth: 1, borderBottomColor: Colors.border },
    pickerWrapper:   { backgroundColor: Colors.bg, borderRadius: 10, borderWidth: 1, borderColor: Colors.border, overflow: 'hidden', justifyContent: 'center' },
    picker:          { height: Platform.OS === 'android' ? 50 : 40, color: Colors.text, marginVertical: Platform.OS === 'android' ? -8 : 0 },

    formOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
    formCard: {
        backgroundColor: Colors.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24,
        maxHeight: '90%', paddingHorizontal: PAD,
        paddingBottom: Platform.OS === 'ios' ? 34 : 20,
    },
    formHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 16 },
    formTitle:  { fontSize: 18, fontWeight: '700', color: Colors.text },
    closeBtn:   { width: 32, height: 32, borderRadius: 16, backgroundColor: Colors.bg, justifyContent: 'center', alignItems: 'center' },

    logoPicker:       { alignItems: 'center', marginBottom: 20 },
    logoCircle:       { width: 90, height: 90, borderRadius: 45, overflow: 'hidden', position: 'relative' },
    logoImg:          { width: 90, height: 90, borderRadius: 45 },
    logoPlaceholder:  { width: 90, height: 90, borderRadius: 45, backgroundColor: Colors.accentLight, justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: Colors.accentBdr, borderStyle: 'dashed' },
    logoPlaceholderText: { fontSize: 12, color: Colors.accent, marginTop: 4 },
    logoEditBadge:    { position: 'absolute', bottom: 4, right: 4, width: 22, height: 22, borderRadius: 11, backgroundColor: Colors.accent, justifyContent: 'center', alignItems: 'center' },

    fieldWrap:       { marginBottom: 14 },

    deleteCard:       { backgroundColor: Colors.surface, borderRadius: 20, padding: 24, alignItems: 'center', width: '100%' },
    deleteIconWrap:   { width: 64, height: 64, borderRadius: 32, backgroundColor: Colors.dangerBg, justifyContent: 'center', alignItems: 'center', marginBottom: 16 },
    deleteTitle:      { fontSize: 18, fontWeight: '700', color: Colors.text, marginBottom: 8 },
    deleteSub:        { fontSize: 14, color: Colors.textSec, textAlign: 'center', lineHeight: 21, marginBottom: 24 },
    deleteActions:    { flexDirection: 'row', gap: 12, width: '100%' },
    deleteConfirmBtn: { flex: 2, paddingVertical: 13, borderRadius: 12, backgroundColor: Colors.danger, alignItems: 'center' },
    deleteConfirmBtnText: { fontSize: 15, color: '#fff', fontWeight: '700' },

    vipRow:        { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
    vipBadge:      { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
    vipBadgeText:  { color: '#fff', fontSize: 12, fontWeight: '700' },
    vipLabel:      { fontSize: 12, fontWeight: '600' },
    candidateName: { fontSize: 16, fontWeight: '700', color: Colors.text, marginBottom: 4 },
    jobTitleText:  { fontSize: 13, color: Colors.textSec, marginBottom: 2 },
    dateText:      { fontSize: 12, color: Colors.textMuted, marginBottom: 10 },
    statusWrap:    { alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
    statusText:    { fontSize: 12, fontWeight: '700' },

    modalContent:  { backgroundColor: Colors.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, paddingBottom: Platform.OS === 'ios' ? 40 : 24 },
    modalRow:      { fontSize: 14, color: Colors.textSec, marginBottom: 4 },
    modalValue:    { fontWeight: '700', color: Colors.text },
    modalJob:      { fontSize: 14, color: Colors.textSec, marginBottom: 12 },
    cvBtn:         { backgroundColor: Colors.accentLight, borderRadius: 10, paddingVertical: 10, alignItems: 'center', marginBottom: 16, borderWidth: 1, borderColor: Colors.accentBdr },
    cvBtnText:     { color: Colors.accent, fontWeight: '600', fontSize: 14 },
    noteLabel:     { fontSize: 13, fontWeight: '600', color: Colors.text, marginBottom: 6 },
    noteInput:     { backgroundColor: Colors.bg, borderWidth: 1, borderColor: Colors.border, borderRadius: 10, padding: 12, fontSize: 14, color: Colors.text, height: 90, textAlignVertical: 'top', marginBottom: 16 },
    decisionLabel: { fontSize: 13, fontWeight: '600', color: Colors.text, marginBottom: 10 },
    decisionRow:   { flexDirection: 'row', gap: 8, marginBottom: 12 },
    btnAction:     { flex: 1, paddingVertical: 10, borderRadius: 10, alignItems: 'center' },
    btnActionText: { color: '#fff', fontWeight: '700', fontSize: 12 },
    btnClose:      { paddingVertical: 13, borderRadius: 12, borderWidth: 1, borderColor: Colors.border, alignItems: 'center' },
    btnCloseText:  { fontSize: 15, color: Colors.textSec, fontWeight: '600' },

    jobCard: {
        backgroundColor: Colors.surface, borderRadius: 16, padding: 16, marginBottom: 12,
        borderWidth: 1.5, borderColor: Colors.border,
        shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2,
        position: 'relative', overflow: 'hidden',
    },
    jobCardFeatured:    { backgroundColor: '#F0FDF4', borderColor: '#22C55E' },
    featuredRibbon:     { position: 'absolute', top: 0, right: 0, backgroundColor: '#F59E0B', paddingHorizontal: 12, paddingVertical: 5, borderBottomLeftRadius: 12, borderTopRightRadius: 14, zIndex: 99, elevation: 5 },
    featuredRibbonText: { color: '#fff', fontSize: 10, fontWeight: '900', textTransform: 'uppercase' },
    jobCardHeader:      { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10, marginTop: 4 },
    jobCardTitle:       { fontSize: 16, fontWeight: '700', color: Colors.text, marginBottom: 4 },
    jobCardCompany:     { fontSize: 13, color: Colors.textSub },
    jobCardActions:     { flexDirection: 'row', gap: 8, marginTop: 12 },
    editBtn:   { flex: 1, backgroundColor: '#EFF6FF', borderRadius: 8, paddingVertical: 8, alignItems: 'center' },
    editBtnText:   { color: Colors.accent, fontWeight: '700', fontSize: 13 },
    deleteBtn: { flex: 1, backgroundColor: '#FEF2F2', borderRadius: 8, paddingVertical: 8, alignItems: 'center' },
    deleteBtnText: { color: Colors.red, fontWeight: '700', fontSize: 13 },
    boostBtn:  { flex: 1, backgroundColor: '#FFFBEB', borderColor: '#F59E0B', borderWidth: 1, borderRadius: 8, paddingVertical: 8, alignItems: 'center' },
    boostBtnText:  { color: '#D97706', fontWeight: '700', fontSize: 13 },

    jobFormTitle:       { fontSize: 20, fontWeight: '800', color: Colors.text, textAlign: 'center', marginBottom: 20 },
    jobFormInput:       { marginBottom: 12, backgroundColor: Colors.surface },
    jobFormSubmitBtn:   { marginTop: 8, borderRadius: 10, backgroundColor: Colors.accent },
    jobPickerContainer: { borderWidth: 1, borderColor: '#79747E', borderRadius: 4, marginBottom: 12, backgroundColor: '#fff', height: 50, justifyContent: 'center' },
    jobPickerLabel:     { position: 'absolute', top: -10, left: 10, backgroundColor: '#fff', paddingHorizontal: 4, fontSize: 12, color: '#49454F', zIndex: 1 },

    addJobBtn:     { backgroundColor: Colors.accent, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 8 },
    addJobBtnText: { color: Colors.surface, fontWeight: '700', fontSize: 14 },

    boostOverlay:      { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
    boostContent:      { backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, maxHeight: SH * 0.8 },
    boostTitle:        { fontSize: 18, fontWeight: 'bold', marginBottom: 15, textAlign: 'center', color: Colors.text },
    packageCard:         { borderWidth: 1, borderColor: Colors.border, borderRadius: 12, padding: 15, marginBottom: 10, backgroundColor: Colors.surface },
    packageCardSelected: { borderColor: '#6366F1', backgroundColor: '#EEF2FF', borderWidth: 2 },
    packageName:  { fontSize: 16, fontWeight: 'bold', color: Colors.text },
    packagePrice: { fontSize: 15, color: '#6366F1', fontWeight: 'bold', marginTop: 4 },
    packageDesc:  { fontSize: 12, color: Colors.textSub, marginTop: 4 },
    stripeBtn:         { backgroundColor: '#635BFF', borderRadius: 10, paddingVertical: 14, alignItems: 'center', marginTop: 15 },
    stripeBtnDisabled: { backgroundColor: '#A5A2EE' },
    stripeBtnText:     { color: '#fff', fontSize: 16, fontWeight: 'bold' },
    boostCancelBtn:     { paddingVertical: 12, alignItems: 'center', marginTop: 5 },
    boostCancelBtnText: { color: Colors.textSub, fontSize: 14, fontWeight: '500' },

    overviewGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, margin: 20 },
    overviewCard: { width: (SW - PAD * 2 - 12) / 2, backgroundColor: Colors.surface, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: Colors.border, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2 },
    overviewIconWrap: { width: 36, height: 36, borderRadius: 10, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
    overviewIcon:     { fontSize: 18 },
    overviewValue:    { fontSize: 22, fontWeight: '800', letterSpacing: -0.5 },
    overviewLabel:    { fontSize: 12, color: Colors.textMuted, fontWeight: '600', marginTop: 4 },
    metaRow:       { flexDirection: 'row', gap: 12, marginBottom: 20 },
    metaCard:      { flex: 1, backgroundColor: Colors.surface, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: Colors.border },
    metaCardTitle: { fontSize: 11, fontWeight: '700', color: Colors.textMuted, marginBottom: 8, textTransform: 'uppercase' },
    metaBigNum:    { fontSize: 30, fontWeight: '800', letterSpacing: -1 },
    section:       { backgroundColor: Colors.surface, borderRadius: 16, padding: 20, borderWidth: 1, borderColor: Colors.border, margin: 20 },
    sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
    sectionDot:    { width: 8, height: 8, borderRadius: 4, marginRight: 8 },
    sectionTitle:  { fontSize: 16, fontWeight: '700', color: Colors.text },
    periodRow:         { flexDirection: 'row', backgroundColor: Colors.bg, borderRadius: 10, padding: 4, marginBottom: 20, alignSelf: 'flex-start' },
    periodBtn:         { paddingHorizontal: 16, paddingVertical: 6, borderRadius: 8 },
    periodBtnActive:   { backgroundColor: Colors.surface, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2, elevation: 1 },
    periodBtnText:     { fontSize: 13, color: Colors.textMuted, fontWeight: '600' },
    periodBtnTextActive: { color: Colors.accent, fontWeight: '700' },
    chartScroll:   { flexDirection: 'row' },
    barColumn:     { alignItems: 'center', width: 55, marginRight: 8 },
    barValueLabel: { fontSize: 10, fontWeight: '600', color: Colors.textSub, marginBottom: 4 },
    barTrack:      { height: 100, width: 16, backgroundColor: '#F8F9FA', borderRadius: 8, justifyContent: 'flex-end' },
    barFill:       { width: '100%', borderRadius: 8 },
    barXLabel:     { fontSize: 10, color: Colors.textMuted, marginTop: 8, textAlign: 'center' },

    unifiedStatCard: {
        flex: 1,
        backgroundColor: '#fff',
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 2,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 1.5,
        elevation: 2,
    },
    unifiedIconBg: {
        width: 30,
        height: 30,
        borderRadius: 15,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 6,
    },
    unifiedValue: {
        fontSize: 15,
        fontWeight: '700',
        marginBottom: 2,
    },
    unifiedLabel: {
        fontSize: 10,
        color: '#6B7280',
        fontWeight: '500',
        textAlign: 'center',
    },
});